// Transport tests execute the generated Worker boot, then compare real DSP clocks.
const target=Deno.args[0]??new URL('../js/analysis-worker.js',import.meta.url),helper=await Deno.readTextFile(target);
const {createAnalysisWorker,boot}=new Function(helper+';return {createAnalysisWorker,boot:analysisWorkerBoot};')();
const results=[],original={Worker:globalThis.Worker,MessageChannel:globalThis.MessageChannel,URL:globalThis.URL,setTimeout:globalThis.setTimeout,clearTimeout:globalThis.clearTimeout};
const blobs=new Map(),revoked=[],workers=[],ports=[];let serial=0,workerMode='normal';
class Port{constructor(){this.closed=false;this.onmessage=null;this.messages=[];ports.push(this);}start(){this.started=true;}close(){this.closed=true;}postMessage(data){if(this.closed)throw Error('Port is closed');this.messages.push(data);const peer=this.peer;queueMicrotask(()=>{if(!peer.closed&&peer.onmessage)peer.onmessage({data});});}}
class Channel{constructor(){this.port1=new Port();this.port2=new Port();this.port1.peer=this.port2;this.port2.peer=this.port1;}}
class FakeWorker{
 constructor(url){if(workerMode==='constructor-error')throw Error('Blocked Worker');this.url=url;this.terminated=false;this.posts=[];this.mode=workerMode;this.chain=Promise.resolve();workers.push(this);this.self={close:()=>{this.selfClosed=true;},postMessage:data=>queueMicrotask(()=>{if(!this.terminated&&this.onmessage)this.onmessage({data});})};this.loaded=blobs.get(url).text().then(text=>new Function('self',text)(this.self));}
 postMessage(data,transfer=[]){this.posts.push({data,transfer});if(this.mode==='never-ready')return;this.chain=this.chain.then(()=>this.loaded).then(()=>{if(!this.terminated)this.self.onmessage({data});});}
 terminate(){this.terminated=true;}
}
globalThis.Worker=FakeWorker;globalThis.MessageChannel=Channel;globalThis.URL={createObjectURL:blob=>{const key='mock-blob-'+(++serial);blobs.set(key,blob);return key;},revokeObjectURL:url=>revoked.push(url)};
const simpleDSP=`class RhythmDetector {constructor(rate,emit,module){this.rate=rate;this.emit=emit;this.module=module;this.referenceEnabled=true;this.reference={options:{routed:true}};}configure(message){this.emit({type:'configured',value:message.value});}process(mic,time,reference){this.emit({type:'block',time,length:mic.length,micFirst:mic[0],referenceFirst:reference&&reference[0]});}}`;
function ctx(){const listeners=new Set();return {sampleRate:48000,state:'running',addEventListener:(_name,fn)=>listeners.add(fn),removeEventListener:(_name,fn)=>listeners.delete(fn),cancel(){this.state='closed';for(const fn of [...listeners])fn();}};}
const tick=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};
function assert(value,message){if(!value)throw Error(message);}
async function test(name,fn){try{results.push({name,status:'PASS',evidence:await fn()});}catch(e){results.push({name,status:'FAIL',error:String(e)});}}
try{
 await test('Initialization transfers the input port and releases the temporary script URL',async()=>{const output=[],module={compiled:true},a=await createAnalysisWorker(ctx(),3,module,m=>output.push(m),simpleDSP,()=>{});const w=a.worker;assert(w.posts[0].transfer[0]===w.posts[0].data.port,'init port not transferred');assert(w.posts[0].data.wasmModule===module,'compiled module was not supplied');assert(revoked.includes(w.url),'script URL leaked');a.close();assert(w.terminated,'worker survived close');return {initPortTransferred:true,modulePreserved:true};});
 await test('Fallback configuration and transferred paired captures retain FIFO and exact128-frame clocks',async()=>{const output=[],a=await createAnalysisWorker(ctx(),4,null,m=>output.push(m),simpleDSP,()=>{}),mic=Float32Array.from({length:512},(_,i)=>i/512),reference=new Float32Array(512).fill(.25),frame=1923328;a.postMessage({type:'mode',value:'sustained'});a.postMessage({type:'capture',frame,mic,reference});await a.worker.chain;await tick();assert(output[0].type==='configured','configuration reordered behind capture');const blocks=output.filter(m=>m.type==='block');assert(blocks.length===4&&blocks.every((m,i)=>m.time===(frame+i*128)/48000&&m.length===128),'source clocks or subchunks changed');const posted=a.worker.posts.at(-1);assert(posted.transfer.includes(mic.buffer)&&posted.transfer.includes(reference.buffer),'paired buffers were not transferred');a.close();return {sourceTimes:blocks.map(m=>m.time),chunks:blocks.length};});
 await test('The direct audio port keeps capture and configuration order and supplies silent routed reference',async()=>{const output=[],a=await createAnalysisWorker(ctx(),5,null,m=>output.push(m),simpleDSP,()=>{});a.port.postMessage({type:'configure',message:{type:'arm',value:'first'}});a.port.postMessage({type:'capture',frame:1393664,mic:new Float32Array(128),reference:null});a.port.postMessage({type:'configure',message:{type:'mode',value:'last'}});await tick();assert(output.map(m=>m.type).join(',')==='configured,block,configured','direct port FIFO changed');assert(output[1].referenceFirst===0,'silent routed reference was lost');a.close();return output;});
 await test('A malformed paired block fails once and closes worker and both channel handles',async()=>{const failures=[],a=await createAnalysisWorker(ctx(),6,null,()=>{},simpleDSP,e=>failures.push(e.message));a.postMessage({type:'capture',frame:10,mic:new Float32Array(128),reference:new Float32Array(64)});await a.worker.chain;await tick();assert(failures.length===1&&a.worker.terminated&&a.port.closed,'malformed input did not close once');assert(a.postMessage({type:'mode'})===false,'closed transport accepted more work');return {failures};});
 await test('Worker script loading errors reject initialization and clean every resource',async()=>{workerMode='constructor-error';const count=revoked.length,failures=[];let rejected=false;try{await createAnalysisWorker(ctx(),7,null,()=>{},simpleDSP,e=>failures.push(e.message));}catch{rejected=true;}finally{workerMode='normal';}assert(rejected&&failures.length===1&&revoked.length===count+1,'load failure leaked or did not reject');return {failures};});
 await test('A missing initialization handshake has a finite timeout and terminates the Worker',async()=>{workerMode='never-ready';globalThis.setTimeout=(fn,_delay)=>original.setTimeout.call(globalThis,fn,1);const failures=[];let rejected=false;try{await createAnalysisWorker(ctx(),8,null,()=>{},simpleDSP,e=>failures.push(e.message));}catch{rejected=true;}finally{workerMode='normal';globalThis.setTimeout=original.setTimeout;}assert(rejected&&failures.length===1&&failures[0]==='Background audio analysis initialization timed out'&&workers.at(-1).terminated,'handshake timeout did not close initialization with its expected reason');return {failures};});
 await test('Cancellation during initialization terminates without a failure notification',async()=>{workerMode='never-ready';const c=ctx(),failures=[],pending=createAnalysisWorker(c,9,null,()=>{},simpleDSP,e=>failures.push(e.message));c.cancel();let rejected=false;try{await pending;}catch{rejected=true;}finally{workerMode='normal';}assert(rejected&&failures.length===0&&workers.at(-1).terminated,'cancel leaked or reported an intentional failure');return {cancelled:true};});
 await test('Intentional close ignores delayed results and is idempotent',async()=>{const output=[],failures=[],a=await createAnalysisWorker(ctx(),10,null,m=>output.push(m),simpleDSP,e=>failures.push(e.message)),late=a.worker.onmessage;a.close();a.close();late({data:{type:'onset',time:10}});assert(output.length===0&&failures.length===0&&a.port.closed,'closed session received stale output');return {ignoredLateResult:true};});
}finally{Object.assign(globalThis,original);}

await test('The actual Worker boot preserves ordinary detector note decisions and nonzero source timestamps',async()=>{
 const html=await Deno.readTextFile(new URL('../index.html',import.meta.url)),source=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)][0][1],Detector=new Function(source+';return RhythmDetector;')(),rate=48000,base=40.06933333333333,frame=Math.round(base*rate),workerMessages=[],directMessages=[];
 const self={postMessage:m=>workerMessages.push(m),close:()=>{}},input={postMessage(){},start(){},close(){}};new Function('self',source+'\n'+boot)(self);self.onmessage({data:{type:'analysis-init',sampleRate:rate,token:17,port:input,wasmModule:null}});
 const direct=new Detector(rate,m=>directMessages.push(m));for(const message of [{type:'mode',value:'sustained'},{type:'threshold',value:10**(-48/20)},{type:'arm',start:base,duration:3.6},{type:'reference-sync',enabled:true,routed:true,backing:false,id:17}]){input.onmessage({data:{type:'configure',message}});direct.configure(message);}
 const count=rate*2.1;for(let at=0;at<count;at+=512){const size=Math.min(512,count-at),mic=Float32Array.from({length:size},(_,i)=>{const age=(at+i)/rate-.9;if(age<0||age>=.75)return 0;const e=Math.min(1,age/.18,(.75-age)/.055);return .03*e*(Math.sin(2*Math.PI*220*age)+.36*Math.sin(2*Math.PI*440*age)+.19*Math.sin(2*Math.PI*660*age));}),reference=new Float32Array(size);input.onmessage({data:{type:'capture',frame:frame+at,mic,reference}});for(let i=0;i<size;i+=128)direct.process(mic.subarray(i,i+128),(frame+at+i)/rate,reference.subarray(i,i+128));}
 const notes=messages=>messages.filter(m=>m.type==='onset').map(m=>({time:m.time,id:m.id,source:m.source,isolated:m.isolated})),actual=notes(workerMessages),expected=notes(directMessages);assert(expected.length===1,'direct note truth not established');assert(JSON.stringify(actual)===JSON.stringify(expected),'worker changed timestamps or note decisions');assert(!workerMessages.some(m=>m.type==='analysis-error'),'worker boot failed');return {direct:expected,worker:actual};
});
const summary={passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length,scope:'Worker lifecycle and transfer/FIFO protocol mocks execute the actual boot. A real embedded DSP comparison verifies identical note decisions and nonzero audio timestamps; this is not a browser underrun measurement.',results};console.log(JSON.stringify(summary,null,2));Deno.exitCode=summary.failed?1:0;
